#!/bin/bash

set -Eeuo pipefail
if [[ ! -f ./releaser ]]; then
  wget --quiet http://http.archive.ai-traders.com/releaser/1.1.0/releaser || { echo "Cannot download releaser, ignoring."; }
fi
if [[ -f ./releaser ]]; then
  source ./releaser
fi
if [[ ! -f ./docker-ops ]];then
  wget --quiet http://http.archive.ai-traders.com/docker-ops/0.3.3/docker-ops || { echo "Cannot download docker-ops, ignoring."; }
fi
if [[ -f ./docker-ops ]];then
  source ./docker-ops
fi

image_name="terraformide"
image_registry="docker-registry.ai-traders.com"
image_dir="./image"
imagerc_filename="imagerc"

command="$1"
set +u
case "${command}" in
  set_version)
      if [[ -n "$2" ]]; then
        next_version="$2"
      else
        version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
        next_version=$(releaser::bump_patch_version "${version}")
      fi
      releaser::set_version_in_changelog "${changelog_file}" "${next_version}"
      exit $?
      ;;
  verify_version)
      releaser::verify_changelog_version
      exit $?
      ;;
  build)
      image_tag=$(git rev-parse HEAD)
      ( set -x; cd "${image_dir}"; docker build -t "${image_name}:${image_tag}" .; )
      docker_ops::create_imagerc "${image_dir}" "${imagerc_filename}" "${image_name}" "${image_tag}" "${image_registry}"
      docker_ops::push_tmp "${image_name}" "${image_tag}" "${image_registry}"
      exit $?
      ;;
  itest)
      docker_ops::ensure_temp_image "${image_dir}" "${imagerc_filename}"
      echo "Testing image: ${AIT_DOCKER_IMAGE_URL}"
      echo "DOJO_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_URL}\"" > ./Dojofile.to_be_tested
      echo "DOJO_IDENTITY_OUTER=\"$(pwd)/test/integration/identities/full\"" >> ./Dojofile.to_be_tested
      echo "DOJO_WORK_OUTER=$(pwd)/test/integration/test_dojo_work" >> ./Dojofile.to_be_tested
      time bats "$(pwd)/test/integration/end_user"
      exit $?
      ;;
  example)
      docker_ops::ensure_temp_image "${image_dir}" "${imagerc_filename}"
      echo "Testing image: ${AIT_DOCKER_IMAGE_URL}"
      echo "DOJO_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_URL}\"" > ./Dojofile.example
      echo "DOJO_IDENTITY_OUTER=\"$(pwd)/test/integration/identities/full\"" >> ./Dojofile.example
      echo "DOJO_WORK_OUTER=$(pwd)/test/integration/test_dojo_work" >> ./Dojofile.example
      dojo -c ./Dojofile.example
      ;;
  release)
      ./tasks verify_version
      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
      git tag "${version}" && git push origin "${version}"
      exit $?
      ;;
  publish)
      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
      validate_version_is_semver "${version}"
      docker_ops::push_production "${image_dir}"  "${imagerc_filename}" "${image_name}" "${version}" "${image_registry}"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
