version: 2.1

workflows:
  # Environment variables required in CircleCI environment:
  #  - DOCKERHUB_USERNAME
  #  - DOCKERHUB_TOKEN
  docker-terraform-dojo:
    jobs:
      - build
      - itest:
          requires:
            - build
      - release:
          requires:
            - itest
      - publish:
          requires:
            - release

jobs:
  build:
    executor: platform
    steps:
      - setup
      - run:
          command: /bin/bash -c "./tasks verify_version"
      - run:
          command: /bin/bash -c "./tasks build"
      - persist_to_workspace:
          root: ~/repo
          paths:
            - image/imagerc

  itest:
    executor: platform
    steps:
      - setup
      - attach_workspace:
          at: ~/repo
      - run:
          command: /bin/bash -c "./tasks itest"

  release:
    executor: platform
    steps:
      - setup
      - run:
          command: /bin/bash -c "./tasks release"

  publish:
    executor: platform
    steps:
      - setup
      - attach_workspace:
          at: ~/repo
      - run:
          command: /bin/bash -c "./tasks publish"

commands:
  setup:
    steps:
      - checkout

executors:
  platform:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/repo
